Repository UBC-MDS/magmavizR, pull requests merged in 2022-01, with the labels that each got.

#24 Scatterplot R Function with tests
  R/scatterplot.R
Labels: enhancement

#25 Test scatterplot
  tests/testthat/test-scatterplot.R
Labels: enhancement

#33 scatterplot.R enhancement
  R/scatterplot.R
Labels: enhancement

#34 Change function call
  tests/testthat/test-histogram.R
Labels: bug

#35 Added packages to DESCRIPTION
  DESCRIPTION
Labels: documentation

#37 "feat: updated INSTALLATION and USAGE sections in the README"
  DESCRIPTION
  README.Rmd
  README.md
  man/figures/README-unnamed-chunk-4-1.png
  man/figures/README-unnamed-chunk-5-1.png
  man/figures/README-unnamed-chunk-6-1.png
  man/figures/README-unnamed-chunk-7-1.png
Labels: documentation

#38 feat: add codecov badge to README
  .Rbuildignore
  DESCRIPTION
  README.Rmd
  README.md
  codecov.yml
Labels: documentation, enhancement

#39 fix: hide installation chunk from README.md
  README.Rmd
  README.md
Labels: bug

#40 fix: include = FALSE for code chunk showing on README
  README.Rmd
  README.md
Labels: bug

#41 update description for histogram function in README
  README.Rmd
  README.md
Labels: documentation
